NAME = libft.a
SRC_DIR = srcs
INCLUDES_DIR = INCLUDES_DIR
SRCS = $(SRC_DIR)/ft-putchar.c $(SRC_DIR)/ft_swap.c $(SRC_DIR)/ft_putstr.c $(SRC_DIR)/ft_strlen.c
CC = gcc
CFLAGS = -Wall -Wextra -Werror
RM = rm -f
